version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:rNT34mzgSxSv5YD9xGiz/JZNKlBDLypPnPKSKlgAhPU=
     # APP_URL=http://localhost  
      DB_HOST: db  
      DB_PORT: 3306
      DB_DATABASE: mydatabase
      DB_USERNAME: user
      DB_PASSWORD: Pass@123
   # env_file:
     # - .env.example
    volumes:
      - app-data:/var/www/html   
    depends_on:
      - db
    container_name: my-php-app-container  
  

  db:
    build:
      context: . 
      dockerfile: Dockerfile-db  
    #image: mysql:8.0  
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: mydatabase  
      MYSQL_USER: user  
      MYSQL_PASSWORD: Pass@123  
    ports:
      - "3306:3306"  
    volumes:
      - db-data:/var/lib/mysql  
    container_name: mydb_container

volumes:
  app-data: 
  db-data:   
